---
title: "Preprocessing (single waves)"
author: "Shozen Dan"
date: "2022-07-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE}
library(data.table)
library(stringr)
library(ggplot2)
library(pammtools)

source("../R/covimod-utility.R")
source("../R/stan-utility.R")
```

## Setup
```{r}
covimod <- load_covimod_data("/Users/mac/Documents/M4R/code")
dt.part <- covimod$part
dt.nhh <- covimod$nhh
dt.hh <- covimod$hh

# Limit to first 5 waves
dt.part <- dt.part[wave <= 5]
dt.nhh <- dt.nhh[wave <= 5]
dt.hh <- dt.hh[wave <= 5]
```

```{r}
covimod
```
```{r}
nrow(dt.hh[wave==1])
```


```{r}
dt.part
```


```{r}
dt.nhh
```

```{r}
dt.hh
```



## Participant data
```{r}
# Remove participants with missing age-strata or gender information
dt.part <- dt.part[!is.na(gender) & !is.na(age_strata)]

# Impute children age by sampling from uniform distribution
dt.part <- impute_child_age(dt.part, seed=1527)

# Sanity check
dt.part[, .(N = .N), by=.(wave)]
```

## Non-household contacts
### Ambiguous contacts
```{r}
# Identify contacts with missing age and gender
dt.amb <- dt.nhh[(is.na(alter_age_strata) | is.na(alter_gender))]

# Append participant info
dt.amb <- merge(dt.amb[,.(new_id, wave)], dt.part, by=c("new_id", "wave"), all.x = TRUE)

# Treat all as missing (some have either gender or age-strata info)
dt.amb <- dt.amb[, .(y_amb = .N), by=c("new_id", "wave")]

# Quick visualization
hist(dt.amb$y_amb)
```

```{r}
# Truncate at 30 (to remove extreme cases where people reported 30+ contacts)
# no, this is merging with participant data instead
dt.amb <- merge(dt.amb, dt.part, by=c("new_id", "wave"), all.x = T)

# Remove ambiguous contacts from original nhh data
dt.nhh <- dt.nhh[!(is.na(alter_age_strata) | is.na(alter_gender))]
```


```{r}
dt.amb
```


### Group contacts
```{r}
SDcols_Q75 <- c("Q75_u18_work", "Q75_u18_school", "Q75_u18_else",
                "Q75_1864_work", "Q75_1864_school", "Q75_1864_else",
                "Q75_o64_work", "Q75_o64_school", "Q75_o64_else")

dt.part[, y_grp := rowSums(.SD, na.rm = T), .SDcols = SDcols_Q75]
dt.part[y_grp > 60, y_grp := 60]

dt.grp <- dt.part[, .(y = sum(y_grp)), by=.(wave, imp_age, gender)]
setnames(dt.grp, "imp_age", "age")
```

```{r}
dt.grp
```


```{r}
dt.hh
```
```{r}
dt.hh[(is.na(alter_age_strata) | is.na(alter_gender))]
```

## Combine household and non-household data
```{r}
setnames(dt.hh, "hh_met_this_day", "y")
dt.hh$type <- "hh"

dt.nhh$y <- 1
dt.nhh$type <- "nhh"

# Combine household and non-household contacts
dt.cmb <- rbind(dt.nhh[,.(new_id, wave, type, alter_age_strata, alter_gender, y)], 
                dt.hh[,.(new_id, wave, type, alter_age_strata, alter_gender, y)])

dt.cmb$type <- factor(dt.cmb$type, levels=c("hh", "nhh"))
setorder(dt.cmb, wave, new_id)

# Merge with participant data
dt.cmb <- merge(dt.cmb, dt.part, by=c("new_id", "wave"), all.x = TRUE)

# Sanity check
sum(dt.cmb$y, na.rm = T) + sum(dt.amb$y_amb) + sum(dt.grp$y)
```


```{r}
dt.cmb
```

## Aggregate contacts
```{r}
# Participant size by wave and repetition
dt.part.size <- dt.part[, .(N = .N), by=.(wave, imp_age, gender)]
setnames(dt.part.size, "imp_age", "age")
dt.part.size

```
```{r}
# Aggregate by household type
dt.cmb <- dt.cmb[, hhsize:= mean(hh_p_incl_0), by=.(wave, type, imp_age, gender, alter_age_strata, alter_gender)]
dt.cmb.h <- dt.cmb[, .(y = sum(y, na.rm=TRUE)), by=.(wave, type, imp_age, gender, alter_age_strata, alter_gender, hhsize)]
setnames(dt.cmb.h, "imp_age", "age")

dt.cmb.h
```

```{r}
dt.cmb.hh <- dt.cmb.h[dt.cmb.h$type=="hh"]
dt.cmb.hh <- dt.cmb.hh[, .(wave, age, gender, alter_age_strata, alter_gender, hhsize, y)]
dt.cmb.hh
```


```{r}
# # Aggregate ambiguous contacts
# dt.amb.agg <- dt.amb[, .(y_amb = sum(y_amb, na.rm=TRUE)), by=.(wave, imp_age, gender)]
# setnames(dt.amb.agg, c("imp_age", "y_amb"), c("age", "y"))

```

```{r}
# # Aggregate age-gender-specific contacts
# dt.cmb.hh.agg <- dt.cmb.hh[, .(y = sum(y, na.rm=TRUE)), by=.(wave, age, gender, alter_age_strata, alter_gender)]
# not needed, already unique age-gender combinations

# # Aggregate ambiguous contacts
# dt.amb.agg <- dt.amb[, .(y_amb = sum(y_amb, na.rm=TRUE)), by=.(wave, imp_age, gender)]
# setnames(dt.amb.agg, c("imp_age", "y_amb"), c("age", "y"))

# # Total number of contacts (specific + ambiguous + group)
# dt.cmb.agg.margin <- dt.cmb.agg[,.(y = sum(y, na.rm=TRUE)), by=.(wave, age, gender)]
# dt.tot <- rbind(dt.cmb.agg.margin, dt.amb.agg, dt.grp)
# dt.tot <- dt.tot[,.(y = sum(y, na.rm=TRUE)), by=.(wave, age, gender)]
# setnames(dt.tot, "y", "y_tot")

dt.cmb.hh.margin <- dt.cmb.hh[,.(y = sum(y, na.rm=TRUE)), by=.(wave, age, gender)]

# Calculate zeta term, proportion of detailed age information S_{ta}^g
# we are assuming for households this is equal to 1 for every observations
# delete the observations with missing age and gender contact information
dt.cmb.hh.margin[, zeta := 1]

# Offset terms
dt.offsets <- merge(dt.part.size, dt.cmb.hh.margin[,.(wave, age, gender, zeta)], 
                    by=c("wave","age","gender"), all.y = TRUE)
dt.offsets[is.na(zeta), zeta := 1]
dt.offsets <- dt.offsets[!is.na(age) & !is.na(gender)]
```

```{r}
dt.offsets
```


```{r}
# Remove participants and contacts 85+
dt.cmb.hh <- dt.cmb.hh[!(age > 84 | alter_age_strata == "85+")]
dt.offsets <- dt.offsets[!(age > 84)]

# Remove remaining NAs
dt.cmb.hh <- dt.cmb.hh[!is.na(alter_gender)]

g <- make_grid(85, 5, gender = TRUE)
setnames(g, "u", "wave")
d <- merge(g, dt.cmb.hh, by=c("wave", "age", "gender", "alter_age_strata", "alter_gender"), all.x = TRUE)
d <- merge(d, dt.offsets, by = c("wave", "age", "gender"), all.x = TRUE)

# Impute true zeroes
d <- d[!is.na(N)]
d <- d[is.na(y), zeta := 1]
d <- d[is.na(y), y := 0]
```


```{r}
# d[zeta!=1]
d
```

```{r}
# View(d[gender == "Male" & alter_gender == "Male"])
```

```{r}
# d1 <- complete(dt.offsets[gender == "Male"], age = 0:84, fill = list(N = 1, zeta = 1))
# View(dt.offsets[gender == "Male"])
# View(d1)
```

```{r}
fig.path = "/Users/mac/Documents/M4R/code/bayes_consistency_rate/bayes-rate-consistency-selena/notebooks/COVIMOD-preprocessing_files/figure-html"

tmp <- d[, m := y/N]
```


```{r}
p1 <- ggplot(tmp[wave==1, ], aes(age, alter_age_strata)) + 
  geom_tile(aes(fill = m)) + 
  facet_grid(gender ~ alter_gender) + 
  viridis::scale_fill_viridis(option='H') +
  theme_bw() + 
  labs(x = "Age of participants", y = "Age of contacts", fill = "Empirical contact intensity") +
  theme(aspect.ratio = 1, legend.position = "bottom", text = element_text(size=5))

p1
ggsave(file.path(fig.path, paste0("empirical-contact-intensity-hh-wave1.png")), plot = p1)

p2 <- ggplot(tmp[wave==1, ], aes(age, alter_age_strata)) + 
  geom_tile(aes(fill = log(y))) + 
  facet_grid(gender ~ alter_gender) + 
  viridis::scale_fill_viridis(option='H') +
  theme_bw() + 
  labs(x = "Age of participants", y = "Age of contacts", fill = "Logarithm of contact counts") +
  theme(aspect.ratio = 1, legend.position = "bottom", text = element_text(size=5))

p2
ggsave(file.path(fig.path, paste0("log-contact-counts-hh-wave1.png")), plot = p2)
```
```{r}
d
```
```{r}
d[is.na(hhsize), hhsize := 0]
d[, hhsize_round := ceiling(hhsize) ]
d[, hhsize_plot := fcase(
  hhsize_round == 2, "Household size 2",
  hhsize_round == 3, "Household size 3",
  hhsize_round == 4, "Household size 4",
  hhsize_round == 5, "Household size 5",
  hhsize_round >= 6, "Household size 6+",
  default = NA
) ]
d[, gender_comb := fcase(
  gender == "Male" & alter_gender == "Male", "Male to Male",
  gender == "Male" & alter_gender == "Female", "Male to Female",
  gender == "Female" & alter_gender == "Male", "Female to Male",
  gender == "Female" & alter_gender == "Female", "Female to Female",
  default = NA
)]
```
```{r}
d[complete.cases(d), ]
```
```{r}
d
```


```{r}
p3 <- ggplot(d[complete.cases(d)  & wave==1, ], aes(age, alter_age_strata)) + 
  geom_tile(aes(fill = m)) + 
  facet_grid(hhsize_plot~gender_comb) + 
  viridis::scale_fill_viridis(option='H') +
    scale_x_continuous(expand = c(0,0)) +
  scale_y_discrete(expand = c(0,0)) +
  theme_bw() + 
  labs(x = "Age of participants", y = "Age of contacts", fill = "Empirical contact intensity") +
  theme(aspect.ratio = 1, legend.position = "bottom",strip.background = element_rect(color=NA, fill = "transparent"), text = element_text(size=5))

p3
ggsave(file.path(fig.path, paste0("empirical-contact-intensity-hh-per-hhsize-wave1.png")), plot = p3)

p4 <- ggplot(d[complete.cases(d) & wave==1, ], aes(age, alter_age_strata)) + 
  geom_tile(aes(fill = log(y))) + 
  facet_grid(hhsize_plot~gender_comb) + 
  viridis::scale_fill_viridis(option='H') +
  scale_x_continuous(expand = c(0,0)) +
  scale_y_discrete(expand = c(0,0)) +
  theme_bw() + 
  labs(x = "Age of participants", y = "Age of contacts", fill = "Logarithm of contact counts") +
  theme(aspect.ratio = 1, legend.position = "bottom", strip.background = element_rect(color=NA, fill = "transparent"), text = element_text(size=5))

p4
ggsave(file.path(fig.path, paste0("log-contact-counts-hh-per-hhsize-wave1.png")), plot = p4)
```
```{r}
p5 <- ggplot(d[complete.cases(d) & wave == 1, ], aes(age, alter_age_strata)) + 
  geom_tile(aes(fill = y)) + 
  facet_grid(hhsize_plot~gender_comb) + 
  viridis::scale_fill_viridis(option='H') +
  theme_bw() + 
  scale_x_continuous(expand = c(0,0)) +
  scale_y_discrete(expand = c(0,0)) +
  labs(x = "Age of participants", y = "Age of contacts", fill = "Contact counts") +
  theme(aspect.ratio = 1, legend.position = "bottom", strip.background = element_rect(color=NA, fill = "transparent"), text = element_text(size=5))

p5
ggsave(file.path(fig.path, paste0("contact-counts-hh-per-hhsize-wave1.png")), plot = p5)
```


## Export data
```{r}
covimod.single <- list(
  contacts = d,
  offsets = dt.offsets,
  pop = covimod$pop
)

data.path = "/Users/mac/Documents/M4R/code/bayes_consistency_rate"
saveRDS(covimod.single, file=file.path(data.path, "data/COVIMOD/COVIMOD-single-hh.rds"))
```

