---
title: "Preprocessing (single waves)"
author: "Shozen Dan"
date: "2022-07-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE}
library(data.table)
library(stringr)
library(ggplot2)
library(pammtools)

source("../R/covimod-utility.R")
source("../R/stan-utility.R")
```

## Setup
```{r}
covimod <- load_covimod_data("/Users/mac/Documents/M4R/code")
dt.part <- covimod$part
dt.nhh <- covimod$nhh
dt.hh <- covimod$hh

# Limit to first 5 waves
dt.part <- dt.part[wave <= 5]
dt.nhh <- dt.nhh[wave <= 5]
dt.hh <- dt.hh[wave <= 5]
```

```{r}
covimod
# dt.part
# dt.nhh
# dt.hh
```

## Participant data
```{r}
# Remove participants with missing age-strata or gender information
dt.part <- dt.part[!is.na(gender) & !is.na(age_strata)]

# Impute children age by sampling from uniform distribution
dt.part <- impute_child_age(dt.part, seed=1527)

# Sanity check
dt.part[, .(N = .N), by=.(wave)] # total for all waves gives 7482
```

## Non-household contacts
### Ambiguous contacts
```{r}
# Identify contacts with missing age and gender
dt.amb.nhh <- dt.nhh[(is.na(alter_age_strata) | is.na(alter_gender))]

# Append participant info
dt.amb.nhh <- merge(dt.amb.nhh[,.(new_id, wave)], dt.part, by=c("new_id", "wave"), all.x = TRUE)

# Treat all as missing (some have either gender or age-strata info)
dt.amb.nhh <- dt.amb.nhh[, .(y_amb = .N), by=c("new_id", "wave")]

# Quick visualization
hist(dt.amb.nhh$y_amb)
```

```{r}
# Truncate at 30 (to remove extreme cases where people reported 30+ contacts)
# no, this is merging with participant data instead
dt.amb.nhh <- merge(dt.amb.nhh, dt.part, by=c("new_id", "wave"), all.x = TRUE)

# Remove ambiguous contacts from original nhh data
dt.nhh <- dt.nhh[!(is.na(alter_age_strata) | is.na(alter_gender))]

# add contact count for each nhh single contacts for non-ambiguous data
dt.nhh$y <- 1
```


```{r}
dt.amb.nhh
dt.nhh
```


### Group contacts
```{r}
# this is also part of non-household
SDcols_Q75 <- c("Q75_u18_work", "Q75_u18_school", "Q75_u18_else", 
                "Q75_1864_work", "Q75_1864_school", "Q75_1864_else",
                "Q75_o64_work", "Q75_o64_school", "Q75_o64_else")

dt.part[, y_grp := rowSums(.SD, na.rm = T), .SDcols = SDcols_Q75]
dt.part[y_grp > 60, y_grp := 60]

dt.grp <- dt.part[, .(y = sum(y_grp)), by=.(wave, imp_age, gender)]
setnames(dt.grp, "imp_age", "age")
```

```{r}
dt.grp
# dt.hh
# dt.hh[(is.na(alter_age_strata) | is.na(alter_gender))]
# dt.nhh
```


# Only non-household data
```{r}
# Merge with participant data
dt.cmb.nhh <- merge(dt.nhh, dt.part, by=c("new_id", "wave"), all.x = TRUE)
# we are only keeping the intersecting rows in terms of new_id and wave, right?
# we have already merged nhh and dt.grp so everything is fine
dt.cmb.nhh
```

## Aggregate contacts
```{r}
# Participant size by wave and repetition
dt.part.size <- dt.part[, .(N = .N), by=.(wave, imp_age, gender)]
setnames(dt.part.size, "imp_age", "age")

# dt.part.size

# Aggregate non-household
dt.cmb.agg.nhh <- dt.cmb.nhh[, .(y = sum(y, na.rm=TRUE)), by=.(wave, imp_age, gender, alter_age_strata, alter_gender)]
setnames(dt.cmb.agg.nhh, "imp_age", "age")

# dt.cmb.agg.nhh

# Aggregate ambiguous contacts
dt.amb.agg.nhh <- dt.amb.nhh[, .(y_amb = sum(y_amb, na.rm=TRUE)), by=.(wave, imp_age, gender)]
setnames(dt.amb.agg.nhh, c("imp_age", "y_amb"), c("age", "y"))

# Total number of contacts (specific + ambiguous + group)
dt.cmb.agg.margin.nhh <- dt.cmb.agg.nhh[,.(y = sum(y, na.rm=TRUE)), by=.(wave, age, gender)]

dt.tot <- rbind(dt.cmb.agg.margin.nhh, dt.amb.agg.nhh, dt.grp) # change dt.grp to only be the nhh contacts? ask about the else categ.
dt.tot <- dt.tot[,.(y = sum(y, na.rm=TRUE)), by=.(wave, age, gender)]
setnames(dt.tot, "y", "y_tot")

# Calculate zeta term, proportion of detailed age information S_{ta}^g
dt.amb.agg.margin.nhh <- merge(dt.cmb.agg.margin.nhh, dt.tot, by=c("wave", "age","gender"), all.x=TRUE)
dt.amb.agg.margin.nhh[, zeta := y/y_tot]
dt.amb.agg.margin.nhh[, zeta := ifelse(is.nan(zeta), 1, zeta)]
dt.amb.agg.margin.nhh
```

```{r}
# Offset terms
dt.offsets.nhh <- merge(dt.part.size, dt.amb.agg.margin.nhh[,.(wave, age, gender, zeta)], 
                    by=c("wave","age","gender"), all.x = T)
dt.offsets.nhh[is.na(zeta), zeta := 1]

dt.tot[, .(y = sum(y_tot)), by=.(wave)]
```

```{r}
dt.offsets.nhh
```


```{r}
# Remove participants and contacts 85+
dt.cmb.agg.nhh <- dt.cmb.agg[!(age > 84 | alter_age_strata == "85+")]
dt.offsets.nhh <- dt.offsets[!(age > 84)]

# Remove remaining NAs
dt.cmb.agg.nhh <- dt.cmb.agg.nhh[!is.na(alter_gender)]

g <- make_grid(85, 5, gender = TRUE)
setnames(g, "u", "wave")
d <- merge(g, dt.cmb.agg.nhh, by=c("wave", "age", "gender", "alter_age_strata", "alter_gender"), all.x = TRUE)
d <- merge(d, dt.offsets.nhh, by = c("wave", "age", "gender"), all.x = TRUE)

# Impute true zeroes
d <- d[!is.na(N)]
d <- d[is.na(y), zeta := 1]
d <- d[is.na(y), y := 0]
```

```{r}
d
```


```{r}
hist(d$zeta)
```


```{r}
hist(d$zeta[which(d$zeta != 1)])
```



## Export data
```{r}
covimod.single <- list(
  contacts = d,
  offsets = dt.offsets.nhh,
  pop = covimod$pop
)

data.path = "/Users/mac/Documents/M4R/code"
saveRDS(covimod.single, file=file.path(data.path, "data/COVIMOD/COVIMOD-single-nhh.rds"))
```

