---
title: "Preprocessing (single waves)"
author: "Shozen Dan"
date: "2022-07-31"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r message=FALSE}
library(data.table)
library(stringr)
library(ggplot2)
library(pammtools)
library(dplyr)

source("../R/covimod-utility.R")
source("../R/stan-utility.R")
```

## Setup
```{r}
covimod <- load_covimod_data("/Users/mac/Documents/M4R/code")
dt.part <- covimod$part
dt.nhh <- covimod$nhh
dt.hh <- covimod$hh

# Limit to first 5 waves
dt.part <- dt.part[wave <= 5]
dt.nhh <- dt.nhh[wave <= 5]
dt.hh <- dt.hh[wave <= 5]
```

```{r}
covimod
```

# ```{r}
# dt.part
# ```
# 
# 
# ```{r}
# dt.nhh
# ```
# 
# ```{r}
# dt.hh
# ```



## Participant data
```{r}
# Remove participants with missing age-strata or gender information
dt.part <- dt.part[!is.na(gender) & !is.na(age_strata)]

# Impute children age by sampling from uniform distribution
dt.part <- impute_child_age(dt.part, seed=1527)

# Sanity check
dt.part[, .(N = .N), by=.(wave)]
dt.part
```

```{r}
# check
# dt.part[is.na(gender)]
# dt.part[is.na(age_strata)]
```


## Household contacts
```{r}
# Remove household contacts with missing age and gender (only 149 hh contacts with missing age and gender info)
dt.hh <- dt.hh[!is.na(alter_age_strata) & !is.na(alter_gender)]
dt.hh

# Merge participant data and household contacts
dt.hh <- merge(dt.hh, dt.part, by=c("new_id", "wave"), all.x=TRUE)
dt.hh
```
```{r}
# # Check
# View(dt.hh[order(wave, new_id), ])
# dt.hh[is.na(alter_age_strata) | is.na(alter_gender)]
# dt.hh[is.na(age) | is.na(gender)]
```

```{r}
# Select relevant columns
d <- dt.hh[, .(new_id, wave, alter_age_strata, alter_gender, job.x, hh_met_this_day, imp_age, gender, hh_p_incl_0, kreis_0, job.y, date)]
d
setnames(d, c("job.x", "hh_met_this_day", "imp_age", "hh_p_incl_0", "kreis_0", "job.y"), c("job_hh_contact", "y", "age", "household_size", "kreis_0", "job_participant"))
d
```
```{r}
# d_reduced <- d[, list(new_id, wave, alter_age_strata, alter_gender, age, gender, household_size, y)]
# # check duplicates for wave 1
# d_reduced_1 <- d_reduced[wave == 1]
# d1 <- d[wave==1]
# d_duplicates_1 <- d1[duplicated(d_reduced_1)]
# View(d_duplicates_1[order(new_id, wave), ])

d_several_hh <- d %>% group_by(new_id, wave, alter_age_strata, alter_gender, age, gender) %>% summarise(n=sum(n())) %>% filter(n>1)
d_several_hh[order(d_several_hh$wave), ]
```

```{r}
d_comb <- merge(d, d_several_hh, by=c("new_id", "wave", "alter_age_strata", "alter_gender", "age", "gender"), all=TRUE)
d_comb 
```
```{r}
d_comb[is.na(n), n := 1]
d_comb
```


```{r}
age_col <- seq(from=1, to=84, by=1)
gender_col <- c("Male", "Female")
alter_age_col <- seq(from=1, to=84, by=1)
alter_gender_col <- c("Male", "Female")
# id_col <- unique(d_comb$new_id)

dt.hh.structure <- expand.grid(age_col, gender_col, alter_age_col, alter_gender_col)
setnames(dt.hh.structure, c("Var1", "Var2", "Var3", "Var4"), c("age", "gender", "alter_age", "alter_gender"))
dt.hh.structure.table <- as.data.table(dt.hh.structure)

dt.hh.structure.table[, alter_age_strata := fcase(
    alter_age <= 4,  "0-4",
    alter_age <= 9,  "5-9",
    alter_age <= 14, "10-14",
    alter_age <= 19, "15-19",
    alter_age <= 24, "20-24",
    alter_age <= 34, "25-34",
    alter_age <= 44, "35-44",
    alter_age <= 54, "45-54",
    alter_age <= 64, "55-64",
    alter_age <= 69, "65-69",
    alter_age <= 74, "70-74",
    alter_age <= 79, "75-79",
    alter_age <= 84, "80-84",
    alter_age > 84, "85+",
    default = NA
  )]

dt.hh.structure <- as.data.frame(dt.hh.structure.table)
dt.hh.structure$alter_age_strata <- factor(
    dt.hh.structure$alter_age_strata,
    levels = c("0-4","5-9","10-14","15-19","20-24","25-34","35-44",
               "45-54","55-64","65-69","70-74","75-79","80-84","85+")
  )
dt.hh.structure
```

```{r}
d_comb_no_dupl <- d_comb %>% distinct(new_id, wave, alter_age_strata, alter_gender, .keep_all=TRUE)

# check
# d_comb_no_dupl %>% group_by(new_id, wave, alter_age_strata, alter_gender, age, gender) %>% summarise(n=sum(n())) %>% filter(n>1)

d_comb_no_dupl  %>% filter(n>1)
```


```{r}
# merge datasets
d.everything <- merge(dt.hh.structure, d_comb_no_dupl, by=c("age", "gender", "alter_gender", "alter_age_strata"), all=TRUE)
d.everything
```

## Combine household and non-household data
```{r}
setnames(dt.hh, "hh_met_this_day", "y")
dt.hh$type <- "hh"

dt.nhh$y <- 1
dt.nhh$type <- "nhh"

# Combine household and non-household contacts
dt.cmb <- rbind(dt.nhh[,.(new_id, wave, type, alter_age_strata, alter_gender, y)], 
                dt.hh[,.(new_id, wave, type, alter_age_strata, alter_gender, y)])

dt.cmb$type <- factor(dt.cmb$type, levels=c("hh", "nhh"))
setorder(dt.cmb, wave, new_id)

# Merge with participant data
dt.cmb <- merge(dt.cmb, dt.part, by=c("new_id", "wave"), all.x = TRUE)

# Sanity check
sum(dt.cmb$y, na.rm = T) + sum(dt.amb$y_amb) + sum(dt.grp$y)
```


```{r}
dt.cmb
```

## Aggregate contacts
```{r}
# Participant size by wave and repetition
dt.part.size <- dt.part[, .(N = .N), by=.(wave, imp_age, gender)]
setnames(dt.part.size, "imp_age", "age")

# dt.part
# dt.part.size

# Aggregate by household type
dt.cmb.h <- dt.cmb[, .(y = sum(y, na.rm=TRUE)), by=.(wave, type, imp_age, gender, alter_age_strata, alter_gender)]
setnames(dt.cmb.h, "imp_age", "age")

# dt.cmb.household

# Aggregate ambiguous contacts
dt.amb.agg <- dt.amb[, .(y_amb = sum(y_amb, na.rm=TRUE)), by=.(wave, imp_age, gender)]
setnames(dt.amb.agg, c("imp_age", "y_amb"), c("age", "y"))

```

```{r}
# Aggregate age-gender-specific contacts
dt.cmb.agg <- dt.cmb[, .(y = sum(y, na.rm=TRUE)), by=.(wave, imp_age, gender, alter_age_strata, alter_gender)]
setnames(dt.cmb.agg, "imp_age", "age")

# dt.cmb.agg
# dt.cmb.agg[(is.na(alter_age_strata) | is.na(alter_gender))]

# Aggregate ambiguous contacts
dt.amb.agg <- dt.amb[, .(y_amb = sum(y_amb, na.rm=TRUE)), by=.(wave, imp_age, gender)]
setnames(dt.amb.agg, c("imp_age", "y_amb"), c("age", "y"))

# Total number of contacts (specific + ambiguous + group)
dt.cmb.agg.margin <- dt.cmb.agg[,.(y = sum(y, na.rm=TRUE)), by=.(wave, age, gender)]
dt.tot <- rbind(dt.cmb.agg.margin, dt.amb.agg, dt.grp)
dt.tot <- dt.tot[,.(y = sum(y, na.rm=TRUE)), by=.(wave, age, gender)]
setnames(dt.tot, "y", "y_tot")

# Calculate zeta term, proportion of detailed age information S_{ta}^g
dt.amb.agg.margin <- merge(dt.cmb.agg.margin, dt.tot, by=c("wave", "age","gender"), all.x=TRUE)
dt.amb.agg.margin[, zeta := y/y_tot]
dt.amb.agg.margin[, zeta := ifelse(is.nan(zeta), 1, zeta)]

# Offset terms
dt.offsets <- merge(dt.part.size, dt.amb.agg.margin[,.(wave, age, gender, zeta)], 
                    by=c("wave","age","gender"), all.x = T)
dt.offsets[is.na(zeta), zeta := 1]

dt.tot[, .(y = sum(y_tot)), by=.(wave)]
```

```{r}
dt.offsets
```


```{r}
# Remove participants and contacts 85+
dt.cmb.agg <- dt.cmb.agg[!(age > 84 | alter_age_strata == "85+")]
dt.offsets <- dt.offsets[!(age > 84)]

# Remove remaining NAs
dt.cmb.agg <- dt.cmb.agg[!is.na(alter_gender)]

g <- make_grid(85, 5, gender = TRUE)
setnames(g, "u", "wave")
d <- merge(g, dt.cmb.agg, by=c("wave", "age", "gender", "alter_age_strata", "alter_gender"), all.x = TRUE)
d <- merge(d, dt.offsets, by = c("wave", "age", "gender"), all.x = TRUE)

# Impute true zeroes
d <- d[!is.na(N)]
d <- d[is.na(y), zeta := 1]
d <- d[is.na(y), y := 0]
```




```{r}
d
```


## Export data
```{r}
covimod.single <- list(
  contacts = d,
  offsets = dt.offsets,
  pop = covimod$pop
)

saveRDS(covimod.single, file="../data/COVIMOD/COVIMOD-single.rds")
```

